 
name: CI - Validación ARMÓNICA

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validar-html:
    name: Validar HTML
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar validador HTML
        run: npm install -g html-validate

      - name: Validar index.html
        run: html-validate index.html